# Generated by Django 5.2.17 on 2026-09-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
